packages:
  - apps/*
  - packages/*
  - infra/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@sentry-internal/node-cpu-profiler'
  - '@sentry/cli'
  - '@swc/core'
  - esbuild
  - sharp
  - unrs-resolver

ignoredBuiltDependencies:
  - '@scarf/scarf'
